name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: |
        cd forgedg-packages/white-label/api
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        nohup ./run.sh & sleep 2
        cd ../../poc
        chmod +x demo.sh
        ./demo.sh | tee poc.log
        grep -q "Otrzymane jobId: abc123" poc.log
        grep -q "Aktualny status: queued" poc.log
    - run: |
        cd forgedg-packages
        zip -r forgedg-white-label.zip white-label
    - uses: actions/upload-artifact@v3
      with:
        name: white-label
        path: forgedg-packages/forgedg-white-label.zip
